### ISSUE TITLE
Add reference to the parent tag of the `contentSeparator` tag in its description

### ISSUE THREAD

**Issue by joaopalmeiro** [lezer-parser/highlight#13]
Hi! 👋 

In order to make it easier to identify that the [`contentSeparator` tag](https://lezer.codemirror.net/docs/ref/#highlight.tags.contentSeparator) has the `content` tag as its parent tag in the documentation website, and to be consistent with the other tags, I would like to suggest that this information be added explicitly to the description: https://github.com/lezer-parser/highlight/blob/88ff939d5585514b96cdca5c8eaca6deea6ad03c/src/highlight.ts#L566-L567

The first alternative could be to change `A prose separator` to `A prose [content](#highlight.tags.content) separator`, adding the respective link to the `content` tag. 

The second alternative could be to add `Subtag of [content](#highlight.tags.content).` to the description, similar to what is done for the [`paren` tag](https://lezer.codemirror.net/docs/ref/#highlight.tags.paren), for example.

Let me know your thoughts and if I can open a PR. Thanks!

**Comment by marijnh** [comment]
Good idea. Done in attached patch.
