### ISSUE TITLE
parent.set is not iterable

### ISSUE THREAD

**Issue by zealot09** [lezer-parser/highlight#2]
macOS  chrome  108.0.5359.98

maybe chrome upgrades and has special optimize for circular reference，below tag define will push itself into tag.set makes
circular reference。

```
    /// Define a new tag. If `parent` is given, the tag is treated as a
    /// sub-tag of that parent, and
    /// [highlighters](#highlight.tagHighlighter) that don't mention
    /// this tag will try to fall back to the parent tag (or grandparent
    /// tag, etc).
    static define(parent) {
        if (parent === null || parent === void 0 ? void 0 : parent.base)
            throw new Error("Can not derive from a modified tag");
        let tag = new Tag([], null, []);
        tag.set.push(tag);
        if (parent)
            for (let t of parent.set)
                tag.set.push(t);
        return tag;
    }
```

while debugging in chrome，strange things happened

![image](https://user-images.githubusercontent.com/3133046/207767398-e9df8d70-e0b6-46e6-9949-54ecc323c229.png)

then next line, init name with Tag.define, it turns out with  Object[object] , not an instance of  Tag

![image](https://user-images.githubusercontent.com/3133046/207767550-1a5df361-86e0-493b-93fb-957b91e8d360.png)

and go on, jserror

**Comment by marijnh** [comment]
I can run @lezer/highlight without trouble in Chrome 108. Can you be a bit more specific about how to trigger the problem?

**Comment by zealot09** [comment]
> I can run @lezer/highlight without trouble in Chrome 108. Can you be a bit more specific about how to trigger the problem?

Did u try @lezer/highlight/dist/index.js ? I finally found it's my esbuild config packing with the dist/index.js file occured this problem, I just solve this by modify my esbuild config while requiring dist/index.cjs。

But I think problem still exists

**Comment by marijnh** [comment]
I can't see this happening except if `Tag.define` is called with an argument that's not a `Tag`, and the code in the package definitely doesn't do this. Going to close this until I have a working way to reproduce it.
