### ISSUE TITLE
Tags may be null when using legacy StreamParser.

### ISSUE THREAD

**Issue by yfwz100** [lezer-parser/highlight#5]
Tags may be null/undefined when using legacy StreamParser provided in `@codemirror/language`.

It will break the highlight code in the following position:

https://github.com/lezer-parser/highlight/blame/5b04ee057d7b0b3d54e8814f31a638c2df707fbe/src/highlight.ts#LL244C10-L244C10

> For reference in `@codemirror/language`:
>
> https://github.com/codemirror/language/blob/76955d9a33b9ebe5b3118a1b4a33fa958c13e507/src/stream-parser.ts#L96
>
> The root node does not have tags defined.

**Comment by marijnh** [comment]
If you mean the `tags` argument, that is [defined](https://github.com/lezer-parser/highlight/blob/5b04ee057d7b0b3d54e8814f31a638c2df707fbe/src/highlight.ts#L216) to not be null.

**Comment by yfwz100** [comment]
So... should stream parser be modified to have tags built in?

**Comment by yfwz100** [comment]
Or I have to wrap the classHighlighter with the following code:

```js
syntaxHighlighting({
  style(tags) {
    if (!tags) {
      return null;
    }
    return defaultHighlightStyle.style(tags);
  },
  scope(node) {
    return defaultHighlightStyle.scope?.(node) ?? false;
  }
}),
```

**Comment by marijnh** [comment]
> So... should stream parser be modified to have tags built in?

I don't see why that is necessary. Highlighters are called with an array, not null. I don't see any place where that is not happening.

**Comment by yfwz100** [comment]
I finally find the root cause of the above error. 

It's because `@lezer/common` being downloaded multiple times in node_modules because of the mismatched versions. The NodeProp's ID is determined by a module-specific global counter. If modules are not shared, the ID is not increased. So the ID is messy.
